import MuiProvider from '@/providers/MuiProvider'
import TanstackProvider from '@/providers/TanstackProvider'
import '@/public/styles/globals.css'
import { Box } from '@mui/material'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { Roboto } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      url: '/images/favicon.ico'
    }
  ]
}

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  fallback: ['-apple-system', 'system-ui', 'Helvetica Neue', 'sans-serif']
})

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body id="app" className={roboto.variable}>
        <TanstackProvider>
          <MuiProvider>
            <NextIntlClientProvider messages={messages}>
              <Box className="bg-base">{children}</Box>
            </NextIntlClientProvider>
          </MuiProvider>
        </TanstackProvider>
      </body>
    </html>
  )
}
